-- Run in Azure SQL (query editor) after creating server & DB
CREATE TABLE [dbo].[Users] (
  user_id UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  email NVARCHAR(320) NOT NULL UNIQUE,
  phone_e164 NVARCHAR(20) NOT NULL,
  tz NVARCHAR(64) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE [dbo].[Shifts] (
  shift_id UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
  user_id UNIQUEIDENTIFIER NOT NULL REFERENCES [dbo].[Users](user_id),
  shift_start_utc DATETIME2 NOT NULL,
  shift_start_local DATETIME2 NOT NULL,
  tz NVARCHAR(64) NOT NULL,
  notes NVARCHAR(1000) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  day_before_sent_at DATETIME2 NULL,
  two_hours_sent_at DATETIME2 NULL
);
